spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<database>
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <username>
    password: <password>

  jpa:
    hibernate:
      ddl-auto: create # or validate, create-drop, none as needed

    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  application:
    name: messaging-stomp

  mvc:
    static-path-pattern: /static/**

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  web:
    resources:
      static-locations: classpath:/static,file:profile/

jwt:
  secret: <random password>

server:
  address: 0.0.0.0
  port: 8080

#logging:
#  level:
#    root: debug